### ISSUE TITLE
The e-mail address you entered is invalid.

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#100]
Bug: enter an obviously wrong mail (like 'test') and post comment:
Comment is posted but the warning only comes up when I go make a reply to an existing comment (above the reply form).

**Comment by jacobwb** [comment]
This should be fixed now.

**Comment by Lux-Delux** [comment]
Hmmm, now I don't get any warning, I can just post anywhere.

It works for you?

**Comment by jacobwb** [comment]
Yes it works for me. Did you try logging out?

**Comment by Lux-Delux** [comment]
My bad, seems to work fine, don't know what happened

**Comment by Lux-Delux** [comment]
Ah, it doesn't work with notifications disabled. 

With notifications checked it shows the error message, without it not.

**Comment by jacobwb** [comment]
This should hopefully be truly fixed now.

These type, click, see if it works, type, click, click, see if it works, click-click stuff is the worst, most tedious kind of bugs. The entire JavaScript front-end needs to be rewritten so everything is easier to understand and follow, not to mention the fact that performance and browser support were completely overlooked. Not that it seems to be slow, or incompatible. It's just, messy.

Just a note to self.
