### ISSUE TITLE
Referrer check fails if host URL includes port number

### ISSUE THREAD

**Issue by graphographer** [jacobwb/hashover-next#113]
In hashover-javascript.php, line 61:

```
// Error if the script wasn't requested by this server
if (!empty ($_SERVER['HTTP_REFERER'])) {
	if (!preg_match ('/' . $_SERVER['HTTP_HOST'] . '/i', parse_url ($_SERVER['HTTP_REFERER'], PHP_URL_HOST))) {
		exit ('document.write (\'<b>HashOver</b>: External use not allowed.\');');
	}
}
```
will always fail with a host such as "localhost:8080", common when developing on a local machine.
Changing the conditional to something like 
```
if (explode(':', $_SERVER['HTTP_HOST'])[0] !== parse_url ($_SERVER['HTTP_REFERER'], PHP_URL_HOST))
```
seems to fix it, but this is probably a matter of best practices and security that I'm not so well-versed in, so I defer to your expertise.

**Comment by jacobwb** [comment]
@graphographer

Sorry about that, it should be fixed now, feel free to reopen this if it's not.
