### ISSUE TITLE
do not quit setup.php with exit()

### ISSUE THREAD

**Issue by aoloe** [jacobwb/hashover-next#114]
if hashover is not correctly configured, setup.php will quit with `exit("pertinent message");`

while the message is very helpful:
- in many (many!) years of php programming i have never seen the `exit()` function... people normally use `die()`... if they really need to (but one should mostly avoid a program to get to a `die()`);  
  cf. <http://stackoverflow.com/questions/8031921/exit-exit-exit0-die-die0-how-to-exit-script> for a discussion on it.  
  i really searched where you were defining the `exit()` function...
- as far as i could understand, the normal way to call hashover is through js. if it's true, the error message should be formatted as a proper json structure.  
  currently, the browser's developers tools just complain about a wrong answer (and show it!).
- ideally, the javascript code getting the message, will see that the json structure contains an error and will properly display it in the hashover div.
- ideally, the setup process should not quit when the first error is found, but go through to the end and collect all errors and display return them.  
  the errors do not seem to depend on each other.

**Comment by aoloe** [comment]
i can work on this, if you agree on this issue, and we can agree on a way to improve this part of code...

**Comment by aoloe** [comment]
btw, in noticed that `escape_output()` tries to somehow get the error to be correctly formatted... but in my case it fails. and i'm not sure that a function names `escape_output()` is the best place for putting a js dom manipulation :-)

**Comment by jacobwb** [comment]
The error reporting code is a carryover from 1.0. It doesn't work very well, and it has most definitely been broken from all of the changes made so far.

I intend for the `escape_output ()` function to be entirely removed in favor of each class having their own errors property that can be displayed appropriately upon failure.

1. `die ()` and `exit ()` are the same. Technically, however, `die ()` is an alias for `exit ()`, not the other way around. So `exit ()` is preferred. In C, and many other languages, there is no `die ()` only `exit ()`, so also for this reason `exit ()` is preferred.

2. The default way of using HashOver is indeed as JavaScript, however, HashOver can be used as a normal PHP class and return static HTML as well. For this reason error reporting cannot be JavaScript specific. It can't be returned as JSON, if it executes successfully it should return the JavaScript needed to display the comments, if it fails for any reason it should return the error wrapped in JavaScript needed to display the error.

3. Any PHP error is returned to the browser along with the JavaScript. This causes JavaScript syntax errors. Whether the errors are returned as JSON or not wouldn't make any difference, the browser will still complain.

4. I agree. I believe I've made some preparations to move in that direction. However, some errors do indeed depend on each other. For example, the page URL. If HashOver can't get the page URL, it can't create or return a comment thread. If we let the script run without the page URL it will generate many errors. So while it shouldn't exit, it should have someway to indicate to the methods that they aren't allowed to execute.
