### ISSUE TITLE
settings.php is read twice

### ISSUE THREAD

**Issue by aoloe** [jacobwb/hashover-next#118]
currently,  the `settings.php` file is read twice in two successive lines in `hashover.php` around line 60:

- first in `$this->settings = new Settings()`
- then in `$this->setup = new Setup()` (since Setup extends Settings).

in my eyes, the correct way of handing this is:

- the `Setup` class should not extend `Settings`;
- the `Setup` constructor should be almost empty
- the settings should be passed to `$setup` as:

          $this->settings = new Settings();
          $this->setup = new Setup();
          $this->setup->setSettings($settings); 

  (injection is in most cases better than inheritance...)
- in `Setup`, all reference to `$this->{$settingName}` should be replaced by `$this->settings->{$settingName}`

i can make a patch for it, if you agree with the remarks above.

**Comment by jacobwb** [comment]
This is a bug.

The idea is `Setup` inherits `Settings` to have access to the protected properties. Instantiating `Settings` is probably not necessary, every setting should come from `Setup`, but I believe this was done because it saved some memory. It might not be necessary anymore.

The whole setup process needs improving. The idea is `Settings` holds the options, `Setup` uses those to configure the script, it should move to working that way in the future.

**Comment by aoloe** [comment]
here three commits in my "active" branch that improve a bit the way settings are set:

- <https://github.com/aoloe/hashover-next/commit/04f5a19c27d7549e3c7ae8c310b9a745be245dad>
- <https://github.com/aoloe/hashover-next/commit/76d3b6bc2c9fdd06487154d274af2db92035eb7e>
- <https://github.com/aoloe/hashover-next/commit/85da013ae7943aad397c617d84303ed4270b8e56>

`hashover.php` is now getting the settings from setup, which -- optionally -- can read the local settings from a json file.

i'm not sure if this is a patch i would push as a good one, but it helps me to track which settings i've set for my setup.  
and it could give you some ideas...

**Comment by jacobwb** [comment]
The JSON settings file is planned and already implemented on a local version of HashOver I will push once the settings and setup code has been cleaned up a bit.

**Comment by aoloe** [comment]
my naive solution seems to be working quite well for me right now.
