### ISSUE TITLE
SQL query fail! when use mysql mode

### ISSUE THREAD

**Issue by timxd** [jacobwb/hashover-next#122]
Its ok with sql/xml method.
But use mysql mode,got this

"SQL query fail!"

Mysql database must be connected,I tested already.

I found code 
$create = 'CREATE TABLE IF NOT EXISTS \'' . $setup->threadDirectory . '\' '
in database.php

Seems to create a table,but I cant find table name in setting.php

**Comment by jacobwb** [comment]
SQL support is young yet. This should be fixed now, though.
