### ISSUE TITLE
Moving user settings out of versionned file

### ISSUE THREAD

**Issue by taophp** [jacobwb/hashover-next#126]
Currently, settings are in the file `/hashover/scripts/settings.php`.

* This file is handled by Git: using `git pull` to update the local version of the code leads to a conflict,
* This file is not limited to settings and contains some functional code: the functional code may require some updates in the future, but such update could crush user settings,
* This file is placed quite deeply in the tree with many other similar files, but it is not expected from the user to modify the others.

I suggest to:

* move all the settings out of `/hashover/scripts/settings.php` to another file, let's say `/hashover/config.base.php`, handled by git,
* `config.base.php` will contain nothing else than the default configuration and some useful comments as documentation
* the  user will be required to create another file at the same place, called `config.php`. This one will not be handled by Git. It may be a copy of `config.base.php` with the changes the user need or it will only contains the values to change.
* HashOver will load `config.base.php` first, and then will crush the configuration values with `config.php`.

To be clearer, `config.base.php` should look like:

```php
$config['notificationEmail'] = 'example@exemple.com'; // E-mail for notification of new comments
$config['encryptionKey'] = '8CharKey'; // Unique encryption key
...
```
and `config.php`:

```php
$config['notificationEmail'] = 'realmail@gmail.com';
$config['encryptionKey'] = 'bla';
...
```

So the configuration could be load this way:

```php
include_once('../config.base.php');
include_once('../config.php');
```

**Comment by jacobwb** [comment]
This is already implemented.

You may create a file named `settings.json` in the `hashover` directory. JSON is pretty much a standard for storing settings at this point. There is one important thing about this file, the setting-names-are-hyphenated, not camelCase.

For example...

```json
{
	"form-position": "bottom",
	"icon-mode": "none",

	"field-options": {
		"name": "required",
		"password": "required"
	}
}
```

The above will cause the comment form to be placed at the bottom, disables avatar icons, and sets the name and password fields to required.

I apologize for this not being documented anywhere.
