### ISSUE TITLE
Hashover-next requires mcrypt

### ISSUE THREAD

**Issue by giantkingsquid** [jacobwb/hashover-next#129]
Hi Jacob,
I've been following this project with great excitement for some time now, installed and used 1.0 successfully.

Last night I tried your latest build and got some strange errors. I doubt it's a bug, more likely a config issue but would appreciate your input.

In any browser Hashover fails to display.

Error in Safari:
`[Error] SyntaxError: Unexpected token '<'
    (anonymous function)hashover-javascript.php:1`

Error in Firefox
`<br />
<b>Notice</b>:  Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' in <b>/usr/local/var/www/garden/hashover/scripts/setup.php</b> on line <b>121</b><br />
<br />
<b>Notice</b>:  Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' in <b>/usr/local/var/www/garden/hashover/scripts/setup.php</b> on line <b>121</b><br />
<br />
<b>Fatal error</b>:  Call to undefined function mcrypt_get_iv_size() in <b>/usr/local/var/www/garden/hashover/scripts/encryption.php</b> on line <b>44</b><br />`

Error in php log is the same as the one from Firefox above.

I've checked and I do not have mcrypt loaded. Is mcrypt a requirement for Hashover now and inot the future?

**Comment by giantkingsquid** [comment]
I loaded mcrypt and it now works :)

Cheers.

**Comment by jacobwb** [comment]
@giantkingsquid

Yes, Mcrypt is a dependency. It is the only reasonable approach to securely encrypting user data. Fortunately, Mcrypt is basically a de facto standard for encryption in PHP, so it should be fairly easy to get installed and working. As it would seem, you didn't have too much trouble yourself :-)

Thanks for pointing it out, I'll make sure it's mentioned as a dependency in the 2.0 documentation.

**Comment by jacobwb** [comment]
Commit b1b43855d4c7a2abbb2dfe66ed0a8b2fa758f3c1 should have closed this issue, HashOver no longer uses Mcrypt.

OpenSSL is used instead, which is part of PHP core and shouldn't need installation or setup, and therefore also shouldn't require special documentation.
