### ISSUE TITLE
overriding "Login" class not properly implemented

### ISSUE THREAD

**Issue by SikoSoft** [jacobwb/hashover-next#135]
After looking through the code, I saw that we can override some properties by creating a JSON file. I also saw it was possible to pass in a custom Login class by declaring "loginMethod" within the settings.json file. I did this, and part of the code recognizes it, however not all the code does. I called my class AxisLogin, and this is what I ended up with as the response text of the AJAX request:

<br />
<b>Catchable fatal error</b>:  Argument 2 passed to CommentParser::__construct() must be an instance of Login, instance of AxisLogin given, called in /srv/e-bizz-web-axis-com/document_root/hashover/scripts/hashover.php on line 129 and defined in <b>/srv/e-bizz-web-axis-com/document_root/hashover/scripts/commentparser.php</b> on line <b>47</b><br />

And this is why (in CommentParser's constructor) we can see:

	public function __construct (Setup $setup, Login $login, Locales $locales, Avatars $avatars)
	{

So regardless of what you override the loginMethod to, half the code is still requiring the hard-coded "Login" class.

**Comment by SikoSoft** [comment]
Okay, I've figured out the problem. The Login class *is* needed, and simply wraps around any custom Login class.

I'll admit I was quite confused by the structure of this login code. I would suggest some basic documentation showing how to work with the login mechanism to avoid confusion for others.

**Comment by jacobwb** [comment]
Duly noted.
