### ISSUE TITLE
Easy way to disable cookies entirely

### ISSUE THREAD

**Issue by jacmoe** [jacobwb/hashover-next#138]
It would be nice if there was an option to turn off cookies completely.

Right now, even after disabling login, form cookies are set, and I don't want or need that.
I want my site to be completely cookie free.

The main reason is the EU Cookie Directive that - ironically - usually requires me to show a notice and set a cookie that the notice has been shown.

I already removed Google Analytics, so ...

A global cookie-less option for Hashover would be nice.

**Comment by jacmoe** [comment]
I simply commented out line 57 in `cookies.php` :

	// Set a cookie, with either a specific expiration date or the one in Settings
	public function set ($name, $value = '', $date = '')
	{
		$date = !empty ($date) ? $date : $this->expire;
		//setcookie ($name, $value, $date, '/', $this->domain, $this->secure, true);
	}

Next step is to add a configuration option that gets passed to the cookie class - perhaps a 'no_cookies' boolean?

**Comment by jacmoe** [comment]
`settings.php` :

    // Technical settings
    public $loginMethod		= 'defaultLogin';	// Login method class for handling user login information
    public $secureCookies	= false;			// Whether cookies set over secure HTTPS will only be transmitted over HTTPS
    public $setCookies          = false;                     // Whether cookies are set at all
    public $storesIPAddress	= false;			// Whether to store users' IP addresses

`hashover.php` :

    // Instantiate cookies class
	$this->cookies = new Cookies (
		$this->setup->domain,
		$this->setup->cookieExpiration,
		$this->setup->secureCookies,
            $this->setup->setCookies
	);


`cookies.php` :

    class Cookies
    {
    	public $domain;
    	public $expire;
	public $secure = false;
        public $set_cookies = true;
    
    	public function __construct ($domain, $expire, $secure = false, $setCookies = true)
    	{
            // snipped ...
    	}
    
    	// Set a cookie, with either a specific expiration date or the one in Settings
    	public function set ($name, $value = '', $date = '')
    	{
    		$date = !empty ($date) ? $date : $this->expire;
            if($this->setCookies) {
    		setcookie ($name, $value, $date, '/', $this->domain, $this->secure, true);
            }
    	}

**Comment by jacmoe** [comment]
If you are interested, I could issue a PR - but it would be easier if you just did it yourself (so that I don't have to sign that license transfer thing).

**Comment by jacobwb** [comment]
Good idea!

**Comment by jacmoe** [comment]
Thanks a lot for merging it :)
