### ISSUE TITLE
Be the first to comment - twice

### ISSUE THREAD

**Issue by jacmoe** [jacobwb/hashover-next#140]
![screenshot_20161222_110648](https://cloud.githubusercontent.com/assets/85424/21422185/dfc90fec-c836-11e6-8bf4-6bdad4777b98.png)

Small nitpick, but this could be better.
The section under the title could be "don't be shy" or even hidden.

**Comment by jacobwb** [comment]
I agree.

And this would only require little more than some easy CSS and HTML changes.

Here are some possible defaults, which do you like best?

![screenshot from 2017-01-02 02-17-22](https://cloud.githubusercontent.com/assets/4677622/21587493/fa9bf8ee-d091-11e6-954b-7b94d7dd29d7.png)

**Comment by jacmoe** [comment]
I think perhaps: No comments yet. I like that the best.

'No comments' sounds like a politician. :)

**Comment by jacobwb** [comment]
I will make this change now than.
