### ISSUE TITLE
Initial hide option

### ISSUE THREAD

**Issue by prisae** [jacobwb/hashover-next#144]
I like the change of #140 a lot. My blogs are generally very low on comments, so that is a nice enhancement.

I know that hashover-next is not about new features, but because the above I raise it anyway, as it goes into the same direction of simplifying/minimizing the comments area. I never looked into the internals of hashover-next, so I don't know if this would be an easy implement or not.

I suggest, similar to the `collapseLimit` variable, a boolean `initialHide` variable.
- If  `false` (default), everything remains as it is now.
- if `true`, then the comments-block is completely hidden by default, and only a bar is showing something like "Show x comments (y counting replies)".

I made a mockup with one of your blog entries that hopefully helps to clarify the idea:
![mockup](https://cloud.githubusercontent.com/assets/8020943/21685222/560e1c7a-d326-11e6-8f48-613e7c8dc8e1.jpg)

**Comment by jacobwb** [comment]
I like this idea. I've seen many websites where the comment section is completely hidden until a link or button is clicked, this is rather normal behavior for comment sections nowadays, so I'm all for this change.

However, just for clarity, if you set `$collapseLimit` to `0` you will see that at least the comment thread is entirely collapsed. Are you suggesting an option that just includes the form in that collapse?

**Comment by prisae** [comment]
Yes, I suggest to collapse everything from the inital line 'Post a comment on ...' till the final line 'HashOver Comments - Rss-Feed...'.

**Comment by prisae** [comment]
I currently have it implemented that way in my blogs through the blog-template. But I think it would be a nice feature to have straight within hashover. As you say, many webpages do it this way at the moment, and I like it. I often find myself reading comments even though I do not want to invest that time. If they are not there by default, but I have to consciously click a button, I am less likely to fall into that trap...

**Comment by jacobwb** [comment]
This is now implemented in my local version of HashOver.

I will push the changes soon.

**Comment by prisae** [comment]
Great, looking forward to it!

**Comment by jacobwb** [comment]
This is now implemented, and I'm open to any improvement you may think it needs.

Also, I have changed the name of the setting to `$collapsesUI`. Simply because the current naming convention is based on working sentences, for example...

> echo $this->setup->collapsesUI ? 'yes' : 'no';

**Comment by prisae** [comment]
Sorry for the late reply, just got around to test it.

Yes, that is indeed how I had it in mind, looks very nice, slick!

One thing though: When there is no comment yet, it does not show anything. I am not sure if this is just in my implementation or if it is a bug that exists in this new feature.

**Comment by prisae** [comment]
I created a minimal example showing the problem:
![minimalexample](https://cloud.githubusercontent.com/assets/8020943/24784125/125a76a8-1b16-11e7-890f-5bcaeaf57d6f.png)
You can test it yourself at http://ho-test.werthmuller.org.

**Comment by prisae** [comment]
Great, thanks Jacob, now its perfect.

**Comment by jacobwb** [comment]
Glad to hear it fixes the problem.

What is your opinion on what is displayed without comments?

By default it would say "Show 0 Comments", which I think looks like a bug, so for now it says...

    Post a comment [on "<page title>"]

Where the page title is optional, controlled by the `$displaysTitle` setting.

There are a few alternative options...

1. Post a Comment (always without page title)

2. Show Comments

3. Be the first to comment!

4. No comments yet.

**Comment by prisae** [comment]
The default now is OK, although I personally prefer "Post a Comment (always without page title)" over the one with the page title.

My favourite one is "Be the first to comment!". The advantage of that one is that you see straight away that there are no comments yet. So if you are only interested in reading existing comments, not in posting yourself, you can save yourself to click on it.

**Comment by prisae** [comment]
One more thing surfaced: If there is only one comment, it currently shows 

    Post a comment [on "<page title>"]

as if there would be no comment at all. From two comments onwards it shows 

    Show x Comments

**Comment by jacobwb** [comment]
Thanks for your thoughts, I will probably go with "Be the first to comment!"

The "one comment" bug should now be fixed. Sorry for the delay, I fixed it a while ago, but continued making further changes to the codebase anticipating that work would be done by now, but it's not quite done yet. So rather than waiting longer to push this simple change, I have now pushed it by itself.

**Comment by prisae** [comment]
Yes, that's fixed, thanks!
