### ISSUE TITLE
How to set up for hashover?

### ISSUE THREAD

**Issue by myiq** [jacobwb/hashover-next#155]
I want to put the hashover on the bbb.com host and let aaa.com use <script type = "text / javascript" src = "http://bbb.com/hashover.php"> </ script>. How to set up for hashover?

**Comment by jorgesumle** [comment]
That's not a very good idea. Why would you do that? Also in HTML 5 your syntax (a PHP source in a script tag) is not valid.

I don't think this is possible, but I'm not sure. @jacobwb surely knows. If it is possible, it will be problematic because Hashover assumes it is installed in the server from where you execute it. See these lines from `settings.php`:

```
// Get HTTP parent directory
$document_root = realpath ($_SERVER['DOCUMENT_ROOT']);
$http_directory = mb_substr ($root_directory, mb_strlen ($document_root));
```

**Comment by myiq** [comment]
@jorgesumle I don't think it's a good idea, too. But my hosting don't support the php, so only the use of plug-in way to achieve hashover comments.

**Comment by jacobwb** [comment]
@myiq

You can achieve this by placing your remote domain in the public `$allowedDomains` setting array.

Like so...

```php
public $allowedDomains = array (
	'*.aaa.com'
);
```

This is a fairly new feature, it still needs more testing.

@jorgesumle is correct, HashOver in this setup will only handle one website, the website it's actually hosted on. This shouldn't be much of a problem if you only intend to use HashOver from one website. In the future this will be improved to handle complete multi-site setups, allowing for separate individual comment threads per website, as well as separate settings for each website.

Currently, there is a known issue that causes the user to not be redirected to the comment form of the remote domain. This will be fixed soon.
