### ISSUE TITLE
There is sth wrong about chinese.

### ISSUE THREAD

**Issue by EYHN** [jacobwb/hashover-next#160]
zh-cn:
![g 3 3e tiq1h wqexwa5](https://cloud.githubusercontent.com/assets/13579374/24283555/8299496e-10a1-11e7-9f45-210ba6677a41.png)

en:
![vnjrqzonli tmi_58mxg1wu](https://cloud.githubusercontent.com/assets/13579374/24283554/81614664-10a1-11e7-8000-6333e49871e5.png)

**Comment by jacobwb** [comment]
It's a known issue, fixing it now.
