### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Halyul** [jacobwb/hashover-next#161]
Each time I post a new comment, the webpage seems stuck and the comment will not auto show in the comments area but remain in the text area. Also the console outputs this.
![z uh x 3rbm6npw21 bn](https://cloud.githubusercontent.com/assets/6838450/24319429/817fb300-1156-11e7-8866-7878bc723b93.png)

**Comment by jacobwb** [comment]
Unfortunately that doesn't tell me much about the error.

Can you post the response of the request here for me?

Get the response by doing this...

1. On the console, open the "Network" tab.
2. Click the "Clear" icon button.
3. Post a comment with HashOver.
4. On the network tab click the "postcomments.php" request.
5. A panel to the left will open, click the "Response" tab.

Let me know what it says there.

**Comment by Halyul** [comment]
````
<br />
<b>Notice</b>:  Undefined index: status in <b>/hashover/scripts/writecomments.php</b> on line <b>598</b><br />
{"comment":{"permalink":"c14","name":"halyul","avatar":"https:\/\/secure.gravatar.com\/avatar\/4d38858727bccaa09efba4b7daf0f4ae.png?r=pg&s=45&d=https%3A%2F%2Fc.halyul.cc%2Fhashover%2Fimages%2Favatar.png","subscribed":true,"user-owned":true,"date":"3:33pm\u4eca\u5929","sort-date":1490427180,"body":"test"},"count":"\u76ee\u524d\u670914\u6761\u8bc4\u8bba (15\u6761\u56de\u590d)"}
````

**Comment by Halyul** [comment]
I need to refresh the page to see my comment, or it will remain in the text area

**Comment by jacobwb** [comment]
Yes, any error in the JSON will cause that kind of problem.

Are you posting as admin? If so, I believe I have the fix.

**Comment by Halyul** [comment]
Yes

**Comment by jacobwb** [comment]
I hope this fixes it for you :-)

**Comment by Halyul** [comment]
yep, it fixed 👍
