### ISSUE TITLE
e-mail notification

### ISSUE THREAD

**Issue by a1262344305** [jacobwb/hashover-next#163]
I have used hashover for my blog.But i don't  kown how to set up e-mail notification.Is there any instructions？

**Comment by jorgesumle** [comment]
In `hashover/script/settings.php` there is a variable called `$notificationEmail`. Have you set it to your email?

**Comment by a1262344305** [comment]
I sovled that.It maybe my virtual host serve problem.
Recently a china public social comment system will stop its service.So many are finding new comment system.Because of great firewall of china, disqus does't work.
Thank you for making this nice comment!

**Comment by jacobwb** [comment]
Thank you for your help testing and finding any issues.

If this is no longer a problem, please close the issue.
