### ISSUE TITLE
Changing $language value and Hashover does not work anymore

### ISSUE THREAD

**Issue by Bridouz** [jacobwb/hashover-next#164]
Hi, first thanks a lot for Hashover. I've been using for months on my blog and it's a really nice software.

However I grabbed this morning the latest git version and from now if I change $language to _fr_ Hashover does not show on my blog, _en_ value is working however

EDIT: That's a really poor bug report 'cause I do not have time now to investigate. I will try to fix it tomorrow.

**Comment by jacobwb** [comment]
Thanks. A simple bug was the cause of this. I hope it's fixed now.

**Comment by Bridouz** [comment]
Thanks a lot, it's fixed :+1:
