### ISSUE TITLE
Hashover's JavaScript get blocked by LibreJS.

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#169]
In particular, you get this message by LibreJS:
    
>  WhitelistNONTRIVIAL: an open method similar to xhr.open is used
    https://example.com/hashover-next/hashover/hashover.js

**Comment by jacobwb** [comment]
Standby, HashOver will soon be LibreJS compatible...

**Comment by jorgesumle** [comment]
`hashover-next/api/count-link.php` is detected as non-free.
