### ISSUE TITLE
The main .metadata does not get initialised

### ISSUE THREAD

**Issue by kmlyvens** [jacobwb/hashover-next#172]
It seems that current HashOver version does not create the main `./pages/.metadata` file that is needed by `latest.php` API. `.metadata` files in individual page comments seem to be OK.

I used the current commit 42026bd , changed only `$notificationEmail $encryptionKey $adminName        
$adminPassword` in `settings.php`.

When `latest.php` is called by `<script type="text/javascript" src="/acta/hashover/hashover.js?api=latest&global=yes"></script>`, PHP complains about missing file:

```
[Tue May 16 22:24:12 2017] [error] [client X.X.X.X] PHP Warning:  file_get_contents(./pages/.metadata): failed to open stream: No such file or directory in /var/www/acta/hashover/api/latest.php on line 52, referer: http://localhost/acta/index.php/2016/01/10/novum/
```

File is indeed missing – it is also interesting that `.metadata` is created only after second comment:

```
# find .     # Before posting any comments
.
# find .     # After posting first comment
.
./acta-index-php-2016-01-10-novum
./acta-index-php-2016-01-10-novum/1.xml
# find .     # After posting second comment
.
./acta-index-php-2016-01-10-novum
./acta-index-php-2016-01-10-novum/.metadata
./acta-index-php-2016-01-10-novum/2.xml
./acta-index-php-2016-01-10-novum/1.xml
# find .     # Commenting in a different page
.
./acta-index-php-2016-01-10-novum
./acta-index-php-2016-01-10-novum/.metadata
./acta-index-php-2016-01-10-novum/2.xml
./acta-index-php-2016-01-10-novum/1.xml
./acta-index-php-2016-01-10-hello-world
./acta-index-php-2016-01-10-hello-world/1.xml
# find .     # Commenting in a different page again
.
./acta-index-php-2016-01-10-novum
./acta-index-php-2016-01-10-novum/.metadata
./acta-index-php-2016-01-10-novum/2.xml
./acta-index-php-2016-01-10-novum/1.xml
./acta-index-php-2016-01-10-hello-world
./acta-index-php-2016-01-10-hello-world/.metadata
./acta-index-php-2016-01-10-hello-world/2.xml
./acta-index-php-2016-01-10-hello-world/1.xml
# 
```

I suspect that https://github.com/jacobwb/hashover-next/blob/42026bd67de7aaf434c986dd4bd9d1d7b72007e5/hashover/scripts/writecomments.php#L335 is responsible: `if (!file_exists ($metafile) or !is_writable ($metafile)) {`

I should also mention that using sqlite instead of xml backend does not seem to fix the issue.

**Comment by jacobwb** [comment]
Hello, sorry for the long delay.

Thank you for reporting this issue!

Metadata collection is a beta feature, and the code was a mess. And so, the code for collecting and storing relevant metadata has now been completely rewritten, and how and what kind of information is collected has also changed somewhat.

These changes should fix this problem, but they also mean losing all current metadata. I hope you will be willing to test the new metadata collection and report any issues you find with it.
