### ISSUE TITLE
How to configure E-mail notification?

### ISSUE THREAD

**Issue by icandura** [jacobwb/hashover-next#174]
I installed the Hashover on Ubuntu 16.04 VPS.
I set the variable called `$notificationEmail` in `hashover/script/settings.php`, but it dosen't work.
Should I install the mail server on VPS first? Which mail server can be used by Hashover? Postfix, sendmail or something else?
Or can Hashover use an external SMTP server?

**Comment by jorgesumle** [comment]
> I set the variable called $notificationEmail in hashover/script/settings.php?

That worked for me. 

> Should I install the mail server on VPS first? Which mail server can be used by Hashover? Postfix, sendmail or something else?

You need a mail serve to send emails.

You can test if you can send any email with PHP and you should get an error code that will probably help you identify your problem: https://stackoverflow.com/questions/17533863/how-to-configure-php-to-send-e-mail

**Comment by icandura** [comment]
It works! Thank you~
I installed Postfix and it works.
