### ISSUE TITLE
How can I set the default sort ?

### ISSUE THREAD

**Issue by icandura** [jacobwb/hashover-next#179]
I want to change the default sort to `threaded-by-date`,
Is there a setup option in `settings.php` ?

And when I set the `hashover-sort` to `threaded-by-date`,
All comments will be displayed instead of the number I set in the variable `$collapseLimit`,
I guess that all comments are loaded before they can be sorted, right?

**Comment by AndreaCatania** [comment]
I've implemented this features if my pull request is accepted: https://github.com/jacobwb/hashover-next/pull/180

**Comment by icandura** [comment]
Earlier I solved this problem at the front-end by JavaScript,
`<script type="text/javascript">window.addEventListener('load',
	function() {
		var ssID = 'hashover-sort-select';
		var sortSelect = sort = document.getElementById(ssID);
		sortSelect.selectedIndex = 6;
		sortSelect.onchange()
	},
	false);</script>`
Now I can use your method in the back-end to solve this problem~
Thank you for your work!

**Comment by jacobwb** [comment]
Hello @icandura, I have now made the default sort order configurable. You will find that the comments are sorted but remain collapsed until shown, and that all sort methods are supported.

You can change the sort order from the admin Settings page.

I would appreciate your help testing this new feature.

**Comment by jacobwb** [comment]
I am closing this issue now. If you have any problems with the new default sorting, feel free to open new issues about specific problems.
