### ISSUE TITLE
This project is dead: let's revive it

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#195]
The main programmer isn't accepting any pull request or making any contribution since May 6.

We cannot accept any change or fix any bug because we don't have any rights. Let's fork it. There is no legal problem, as Hashover is under the AGPL. Anyone who wants to accept this task. If nobody does that, I'll have to do it myself, but I must warn you, I don't have much free time.

**Comment by jacobwb** [comment]
Hello, thanks for your interest in HashOver. I am alive, and HashOver is still in development. You must understand that HashOver is my own personally project, it only updates when I want to work on it, or when someone else has written some improvements for it that I want to incorporate.

With that said, huge changes are about to be posted, thanks for sticking around :-)

**Comment by jorgesumle** [comment]
Good to see you around again, @jacobwb :). I thought you lost the interest in the development or you abandoned the project because pull requests were being ignored without any response. With that said, I'm looking forward for those improvements.

**Comment by jacobwb** [comment]
> # "about to be posted"
> -_Jacob Barkdull_ ... 6 months ago.

... the code is going live soon.

**Comment by jorgesumle** [comment]
Great. Your last commits are great.

@jacobwb, I've added [Hashover to the Free Software Directory](https://directory.fsf.org/wiki/Hashover). As the main developer, you may want to add some details (donation links, email, etc.). They still have to approve the page, but meanwhile anyone can edit it.
