### ISSUE TITLE
How to enable external use

### ISSUE THREAD

**Issue by orcmilk** [jacobwb/hashover-next#197]
HashOver no longer works on my blog. I just switched to a different hosting company and also updated my Ghost blog script, so maybe that has something to do with it because it works perfectly fine with my old website using the old Ghost script.

In /home/earthapp/public_html/content/themes/journal/partials/comments.hbs, I have the code:
```
<script type="text/javascript" src="/hashover/hashover.js"></script>
<noscript>You must have JavaScript enabled to use the comments.</noscript>
```

And for example, it would usually show up if you click [write a comment] on http://earthappl.es/death-angel/.

http://earthappl.es/hashover/hashover.js seems to load fine, but http://earthappl.es/hashover/scripts/hashover-javascript.php doesn't (404 error). All directories are set to 0755. Everything else is 0644. I only edited the settings.php and the theme, but I also tried re-installing the script totally fresh without any of the old stuff from my old website and it still doesn't work.

BUT it does work if I host the HashOver script on a subdomain and just use this code on /home/earthapp/public_html/content/themes/journal/partials/comments.hbs:
```
<script type="text/javascript" src="http://grim.earthappl.es/hashover/hashover.js"></script>
<noscript>You must have JavaScript enabled to use the comments.</noscript>
```
It will just say something like "External use is not allowed", but at least something shows up! Since it seems more simple than trying to dig through the Ghost script (I don't know), how can I enable external use?

**Comment by orcmilk** [comment]
Nevermind. If I just delete

```
		// Error if the script wasn't requested by this server
		if ($this->mode === 'javascript' and $this->refererCheck () === false) {
			throw new Exception ('External use not allowed.');
		}
```

then external use is allowed.

**Comment by poVoq** [comment]
Did you change this section in the settings.php?
```
	// External domains allowed to remotely load HashOver scripts
	public $allowedDomains = array (
		// '*.example.com',
		// '*.example.org',
		// '*.example.net'
	);
```

**Comment by jacobwb** [comment]
Hello, sorry for the long delay.

@poVoq is right to point out the `$allowedDomain` setting.

Setting it to something like this...

```php
public $allowedDomains = array (
	'*.earthappl.es'
);
```

Should allow remote use.

I see you are now using Disqus, if you are still interested in getting this working again, please let me know and I will try my best to address the issue or help you configure your setup.

**Comment by lixiang810** [comment]
What if  using hashover 2.0? How should I edit config.json?

**Comment by MladenMladen** [comment]
jacob, thank you for the great work you have been doing on developing hashover. 

i found above var in backed/classes/sensitivesettings.php and i added: googleusercontent.com in the list. this will allow cached page from serp to be shown. i am not sure, but maybe you should consider adding this domain by default. otherwise, whole cached page will be blocked... i am not an seo expert of any kind, but google might raise some red flags in their backed because of this, and that is the last thing we want to happen :) i think this deserves more research, at least...

regards,
mladen
