### ISSUE TITLE
Integration with Shaarli possible?

### ISSUE THREAD

**Issue by poVoq** [jacobwb/hashover-next#199]
Any tips on integrating it with Shaarli?

It has a Discus and an Isso plugin:
https://github.com/kalvn/shaarli-plugin-disqus
https://github.com/shaarli/Shaarli/tree/master/plugins/isso

But I would rather like to run a php app like hashover on the same shared host as my Shaarli.

Thanks for the help.

**Comment by poVoq** [comment]
Ok, I am trying to write a Shaarli plugin for this (programming newbie, beware :( ).

I am using the Isso plugin as a base and seem to have it working (It displayed the errors with the standard email settings on my Shaarli before editing the settings.php), but I get the same error as on the site linked here:
https://github.com/jacobwb/hashover-next/issues/133

After I modified the settings.php (and not the setup.php ;) )

The error shown in the Firefox console is:
`SyntaxError: expected expression, got '<' hashover-javascript.php:1`

This seems to be a strange error as this is the first line of the file:
`<?php namespace HashOver;`

Is it maybe somehow not parsing those .php files right?

By the way, for Hashover-Next it is not necessary to modify the file permissions like explained here for Hashover1 right? http://tildehash.com/?page=hashover

I am running this on a shared OVH host with php7.1 enabled. Hashover database is configured as sqlite (i.e. default nothing changed there).

**Comment by poVoq** [comment]
Ok, I'll try this:
https://github.com/jacobwb/hashover-next/issues/186#issuecomment-337907829

**Comment by poVoq** [comment]
Early alpha:
https://github.com/poVoq/shaarli-plugin-hashover-comments

**Comment by jacobwb** [comment]
Great work! I am not at all familiar with Shaarli, so I won't be of much help in writing this plugin, but if you need any help understanding how HashOver works, let me know.
