### ISSUE TITLE
E-mail notifications don't work

### ISSUE THREAD

**Issue by linuxitux** [jacobwb/hashover-next#201]
Just installed the latest version of hashover-next and applied the patch by poVoq to get it work with PHP 7.1 (https://github.com/poVoq/hashover-next/commit/884fec2b799160a1b78f92c772739d56cfb8e94d). It works very well, but e-mail notifications.
I just checked writecomments.php and realized sendNotification() it's never called. Is this ok? Any help appreciated.

**Comment by poVoq** [comment]
Credit where credit is due: https://github.com/jacobwb/hashover-next/issues/186#issuecomment-337907829

Email notifications are indeed a bit strange. They do work in general on my installation, but sometimes not. No idea why, but my host kind of sucks, so they are probably throttling the sending of emails via php.
I guess the best would be to allow configuring an external SMTP email.

**Comment by linuxitux** [comment]
Well, mine don't work at all. I put some flags in the code to debug sending messages to error_log, and the function ``sendNotification()`` isn't called at all.

**Comment by linuxitux** [comment]
Just pulled the last commit and now it's working like a charm!

**Comment by jacobwb** [comment]
Hi @linuxitux, I'm glad it's working for you now.

I would like to explain a few things, though. Firstly, yes the `sendNotification ()` method is intentionally not used. It is left over from work I started but haven't finished, that work being moving the notifications-related code into a new e-mail-specific class with support for SMTP.

Secondly, I would like to explain when e-mails are sent...

1. A user posts a comment -> Admin gets a notification.
2. A user replies to another person's comment -> Admin and the other person get notifications.
3. A user replies to themself -> Only admin gets a notification.
4. **Admin posts a comment -> No notification is sent to Admin.**
5. **Admin replies to themself -> No notification is sent to Admin.**
6. Admin replies to another person's comment -> Only the other person gets a notification.

This might cause some confusion, but I think it makes sense.
