### ISSUE TITLE
Translating admin dashboard

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#202]
I read this text from the changelog:

> Anyone interested in having the admin page available in another
> language should feel free to translate the text and add the
> necessary strings to the respective locale file, I have already
> made the necessary preparations to facilitate your contribution.

However, I didn't found the preparations you talk about. I just see the English strings without anything special for the translation. Should I use [gettext](https://www.gnu.org/software/gettext/) or did you thought about something similar? Sorry if I missed something very obvious. Just want to contribute with a Spanish translation.

**Comment by jacobwb** [comment]
Sorry, I got a bit ahead of myself. The preparations were made for the admin dashboard to be easily localized, however, I didn't move the text out of the admin dashboard and into the locale files at the time I released the admin dashboard.

I have now done so. You will find the Spanish locale file here:

- [hashover/backend/locales/es.php](https://github.com/jacobwb/hashover-next/blob/master/hashover/backend/locales/es.php)

Everything after the `'source-code'` key is new, and translated roughly to perhaps make the translating easier for you. However, feel free to completely scrap what is there if you need to.

Thank you for your work on the translation.

It would be great to have a proper Spanish locale for the admin dashboard.

And thank you for your interest in contributing to HashOver.
