### ISSUE TITLE
Why are settings replicated?

### ISSUE THREAD

**Issue by linuxitux** [jacobwb/hashover-next#205]
I had to configure my vars in `config/settings.json` in order to get hashover work. Why are they replicated there and inside `backend/classes/settings.php`?

**Comment by jacobwb** [comment]
The `config/settings.json` file stores the default settings, and will be updated when settings are changed from the Settings view on the administration page. You should be able to safely delete this file and only use the `backend/classes/settings.php` file if you want.

The `backend/classes/settings.php` file is now meant to only store the default settings, and for making more advanced configurations. It should not be modified if you can make your desired changes from the Settings view on the administration page.

**Comment by linuxitux** [comment]
Thanks @jacobwb
