### ISSUE TITLE
Disabling "Automatically add HashOver CSS to page" breaks moderation interface

### ISSUE THREAD

**Issue by CyberShadow** [jacobwb/hashover-next#218]
Disabling the option makes sense if the HashOver style is to be integrated with the site style, and the CSS definitions are placed in the site CSS rather than the HashOver theme CSS. However, disabling the option completely breaks the moderation interface. The HashOver comments are [hidden by default in `threads.css`](https://github.com/CyberShadow/hashover-next/blob/7a38fd119dd27b50511d007e3ae2235ab6706a26/hashover/admin/views/moderation/threads.css#L25-L27), and with this option turned off, there is nothing to enable them back, thus resulting in a blank page.

I think that the moderation interface should always use the default theme. HashOver themes may be integrated with the main site to the extent that the CSS definitions wouldn't make sense when removed from context. The only practical reason to use the user-selected theme in the moderation panel would be if it expanded on the default HashOver theme in functionality somehow, but I don't think that's a situation that can occur today.

**Comment by jacobwb** [comment]
Thank you for pointing this out to me, this is now fixed. I have not enforced the default theme on the admin page, as I'm not sure I agree with that. The theme can be changed from the admin page as well, so I think most people will want to see the theme change reflected on the moderation page, and not have to navigate to one of their website's pages to see the change.

However, do let me know what you think, it is easy to change now.
