### ISSUE TITLE
Comments not visible

### ISSUE THREAD

**Issue by Hrishikesh-K** [jacobwb/hashover-next#229]
I'm setting up HashOver on my (I'm developing it, but, the blog is actually of my friend) new website (blog, rather). The URL is: [htps://www.brokenhearts.ml/](https://www.brokenhearts.ml/)

I'm using [Adobe Muse](muse.adobe.com) to develop the website and I have hosted it on [InfinityFree](https://www.infinityfree.net).

The only changes I've made to the code is the CSS; replaced every (5, in total) `#hashover-end-links` with 

```
#hashover-end-links {
    display: none;
}
```

I read one whole [thread](https://github.com/jacobwb/hashover-next/issues/115) about the license stuff, but, my friend doesn't want the links at all, so, had to do it.

But now, I can't see the comments which were visible before the change. See here: [htps://www.brokenhearts.ml/breakups.html](htps://www.brokenhearts.ml/breakups.html) Only the names of the posters are visible.

What can be the problem?

Also, is there any way in which I can display same comments on 2 different pages? I mean, Adobe Muse creates a seperate webpage for the mobile and tablet version in my case. So, users are redirected from https://www.brokenhearts.ml/index.html to https://www.brokenhearts.ml/phone/index.html and https://www.brokenhearts.ml/tablet/index.html when visited from mobile and tablet devices respectively. So, I think that HashOver will create seperate comment directory for each of the 'same' page. Thus,  users will see different comments on desktop, mobile and tablet users. Any way to keep all the 'same' pages with same comments?

**Comment by jacobwb** [comment]
Thank you for reading through the issues before opening a new one.

It would seem you misunderstood [this thread](https://github.com/jacobwb/hashover-next/issues/115), but only slightly.

I notice two problems with the CSS at: [brokenhearts.ml/hashover/themes/default/comments.css](https://www.brokenhearts.ml/hashover/themes/default/comments.css)

The first is that there are two copies of the CSS in the file, as if you pasted the CSS at the end of the file.

Note the second Copyright notice halfway through the file.

The second is this change:

```diff
.hashover .hashover-comment > .hashover-balloon,
+.hashover .hashover-edit-form,
+.hashover #hashover-end-links {
+    display: none;
+}
.hashover .hashover-border-top {
	border-top: 1px solid #AAAAAA;
}
```

This hides the "comment balloon" -- where the comment itself is displayed -- and it also removes the top border of the comment balloon. It sounds like neither of these things is what you want.

I would start over. Replace `/hashover/themes/default/comments.css` with the original file.

And then make this simple change on [line 1108](https://github.com/jacobwb/hashover-next/blob/ed8613fc4adf2404c2b6607cf119f6322d5176ec/hashover/themes/default/comments.css#L1108):

```diff
.hashover #hashover-end-links {
+	display: none;
	margin-top: -12px;
	padding: 18px 0px 5px 0px;
	text-align: center;
}
```

Just in case you aren't familiar with diffs, simply add the green line (without the "+").

**Comment by jacobwb** [comment]
As to your other question.

HashOver will respect a canonical link element in the page head.

Both of these pages:

https://www.brokenhearts.ml/phone/breakups.html
https://www.brokenhearts.ml/tablet/breakups.html

Have this canonical link element:

```html
<link rel="canonical" href="https://www.brokenhearts.ml/breakups.html" />
```

Meaning both of those pages will be treated as the same page as:

https://www.brokenhearts.ml/breakups.html

All three pages should all display the same thread.

As long as any other pages do this same thing, you shouldn't have any problems.

If you find that this isn't the case, and that the pages get different threads, that would be a bug and I would appreciate if you would report it.

**Comment by VHrishikesh** [comment]
@CyberShadow 

Thank you sir. That worked!

**Comment by VHrishikesh** [comment]
Hello! I need to reopen this issue.

I just updated my website and checked my site_global.css. It doesn't have any rule for strong and em anymore. However, styling by `**bold**` and `*italics*` isn't working. It's working when I tried using <b> for bold. You can try it here: https://www.brokenhearts.ml/break-ups.html

What can be the issue now?
