### ISSUE TITLE
Not able to link to comment count

### ISSUE THREAD

**Issue by btayalew** [jacobwb/hashover-next#230]
I have been able to add comments to multiple pages on my website by placing multiple JavaScript tags pointing to the 'count link' API. However, I couldn't get the comment counts to link them to my home page. I used <a href="#comments"><span id="hashover-cmtcount">Post</span> Comments</a> as a link, as recommended under the now closed issue#104 but it didn't work. Did I miss anything there or is there any other way to get the comment counts?

Thanks

**Comment by CyberShadow** [comment]
> However, I couldn't get the comment counts to link them to my home page.

So... you want the comment count links to link to a different page than the page that the comments (whose count is shown on the link) are on?

I think the comment count links should look like this:

```html
<a href="URL-of-target-page#comments" class="hashover-count-link">comment count</a>
```

It works for me (though loading `comments.php` and `count-link.php` on the same page doesn't work for some reason).

**Comment by btayalew** [comment]
Thank you for the quick response. Sorry, I may not have worded my question correctly, I am able to link to the pages where the comments are from any page by putting that link on the page, but what I wanted was to get the counts/numbers of comments on those pages to display on my home page. I couldn't get that.

**Comment by CyberShadow** [comment]
> but what I wanted was to get the counts/numbers of comments on those pages to display on my home page.

Well, that's how you do it: on your home page, you create a link to those pages, make it `class=hashover-count-link"`, and the `count-link.php` script will replace the text of the link with the comment count. What problem did you run into?

Or do you want to do it without creating an actual link? I don't think the code currently allows it, but it should still be possible to fake it (by making the link look and act like normal text) with some CSS. I can make a PR for this if you want.

**Comment by btayalew** [comment]
Excuse my amateurish question. I created the link and made it `class=hashover-count-link`, the `count-link.php` script embeds the whole comment under the link rather than replacing the link text with the comment count. Is this the wrong script: 
`<script type="text/javascript" src="/hashover/comments.php?api=count_link"></script>`?

**Comment by CyberShadow** [comment]
> `<script type="text/javascript" src="/hashover/comments.php?api=count_link"></script>`

I don't know if that's supposed to work. I think that's from hashover v1 ?

This worked for me:

`<script src="/hashover/api/count-link.php"></script>`

**Comment by btayalew** [comment]
Yes, it works! I was caught between two versions. Thank you very much.
