### ISSUE TITLE
Permalink and Page addresses in notification emails

### ISSUE THREAD

**Issue by EdHamilton9** [jacobwb/hashover-next#233]
I have installed hashover-next on my online site, https://myoldohiohome.com, and am testing it on one file, namely https://myoldohiohome.com/articles/testing.php.

I have posted a few sample comments. When I receive notification that the comments are posted, the Permalink and page links are not correct. 

They are like this:

Permalink: https://myoldohiohome.com/articles/articles/#hashover-c1

Page: https://myoldohiohome.com/articles/articles/

and they should be like this:

Permalink: 
https://myoldohiohome.com/articles/testing.php#hashover-c1

Page:
https://myoldohiohome.com/articles/testing.php

Everything is installed as it came out of the box from github. My classes/settings.php file is default except for the time zone. I edited this file manually to make that change.

Thank you,
Ed H

**Comment by CyberShadow** [comment]
It's almost surely because of:

```html
  <link rel="canonical" href="./articles/">
```

The canonical location should be an absolute URL with the full canonical address of the current page.

**Comment by EdHamilton9** [comment]
ok, thank you. That's my sloppy code for the site. I will fix it and try again.
I will mark this closed for now. Thank you.

**Comment by EdHamilton9** [comment]
perfect. thank you

**Comment by EdHamilton9** [comment]
closing again.
