### ISSUE TITLE
Problems with URLs with accents

### ISSUE THREAD

**Issue by jorgesumle** [jacobwb/hashover-next#234]
For some reason, they get saved on different locations. Here is an example from my website:
- `men%c3%a9ame-c%c3%b3digo-de-rastreo-oculto`
- `men%C3%A9ame-c%C3%B3digo-de-rastreo-oculto`

**Comment by jorgesumle** [comment]
> Please let me know if the problem is fixed for you now.

I don't know. When I was trying to test the Git development version (commit bca89cceafd8fd150a3914cba877f3d236374346), I got the following error...

```
<br />
<b>Notice</b>:  Undefined property: HashOver\Setup::$defaults in <b>/var/www/html/Quellcode/hashover-next/hashover/backend/classes/settings.php</b> on line <b>187</b><br />
<br />
<b>Warning</b>:  in_array() expects parameter 2 to be array, null given in <b>/var/www/html/Quellcode/hashover-next/hashover/backend/classes/settings.php</b> on line <b>187</b><br />
```
<b>Warning</b>:  in_array() expects parameter 2 to be array, null given in <b>/var/www/html/Quellcode/hashover-next/hashover/backend/classes/settings.php</b> on line <b>187</b><br />
```

Here is my `settings.json` config file...

```
{
	"language": "es",
	"theme": "freak-spot",
	"uses-moderation": false,
	"pends-user-edits": false,
	"data-format": "json",
	"default-name": "Anónimo",
	"allows-images": true,
	"allows-login": true,
	"allows-likes": true,
	"allows-dislikes": true,
	"uses-ajax": true,
	"collapses-interface": false,
	"collapses-comments": true,
	"collapse-limit": 5,
	"reply-mode": "thread",
	"stream-depth": 3,
	"popularity-threshold": 5,
	"popularity-limit": 2,
	"uses-markdown": true,
	"server-timezone": "Europe\/Madrid",
	"uses-user-timezone": true,
	"uses-short-dates": true,
	"time-format": "H:i",
	"date-format": "d\/m\/Y",
	"displays-title": false,
	"form-position": "bottom",
	"uses-auto-login": true,
	"shows-reply-count": true,
	"count-includes-deleted": true,
	"icon-mode": "image",
	"icon-size": 45,
	"image-format": "png",
	"uses-labels": false,
	"uses-cancel-buttons": true,
	"appends-css": true,
	"appends-rss": true,
	"login-method": "defaultLogin",
	"sets-cookies": true,
	"secure-cookies": false,
	"stores-ip-address": false,
	"allows-user-replies": false,
	"noreply-email": "noreply@example.com",
	"spam-batabase": "remote",
	"spam-check-modes": "php",
	"gravatar-force": false,
	"gravatar-default": "wavatar",
	"minifies-javascript": false,
	"minify-level": 4
}

**Comment by jacobwb** [comment]
Sorry about that! This is probably caused by #237, it should be fixed now.
