### ISSUE TITLE
the background modification of the default Gravatar theme seems to be wrong.

### ISSUE THREAD

**Issue by cn-jiangfei** [jacobwb/hashover-next#237]
if (!in_array ($this->gravatarDefault, $this->defaults, true))

Seems to have an array that doesn't exist！

**Comment by jacobwb** [comment]
Thanks for finding this, it should be fixed now.

**Comment by cn-jiangfei** [comment]
thank you very much!

It would be better if you could modify the sorting of comments!

**Comment by jacobwb** [comment]
I don't know how those too things are related, but yes, I am working on implementing that now, actually. It will likely be done in the next few days, I just need to workout the best way of implementing it.

**Comment by cn-jiangfei** [comment]
Thank you. I will wait patiently.  :D

**Comment by jacobwb** [comment]
Hello again, the default sort order of comments is now configurable! I would appreciate your help in testing this new feature, a lot of code was changed so there may still be some issues.

Also, I am looking into the other issues you reported, hang tight.
