### ISSUE TITLE
There seems to be a serious BUG, and all the comments are out of sight.

### ISSUE THREAD

**Issue by cn-jiangfei** [jacobwb/hashover-next#238]
111

**Comment by cn-jiangfei** [comment]
![bug](https://user-images.githubusercontent.com/17905855/44263992-8d375880-a253-11e8-865d-f713400c952c.png)

**Comment by jacobwb** [comment]
Sorry about this, it is not a bug, just a change in how the HTML templates are written. You need to make a small change to your custom theme. The easiest way to do this is copy the HTML files from the default theme into your custom theme folder.

So copy these files:

1. /guestbook/themes/default/comments.html
2. /guestbook/themes/default/latest.html

Into `/guestbook/themes/jiangfei` replacing the files that are there.

If you don't need custom HTML files, simply delete them, and the default theme HTML files will automatically be used. This way you won't have this problem happen again.

**Comment by cn-jiangfei** [comment]
Thanks, I also found this problem!

**Comment by cn-jiangfei** [comment]
You are a great developer！
