### ISSUE TITLE
Visitor email notifications not working

### ISSUE THREAD

**Issue by timoto** [jacobwb/hashover-next#263]
HashOver has installed and functions as expected front and back end with 1 exception:

Notifications to visitors email are **not** working.

Notifications to my Admin email **are** working.

When replying to a visitor's comment, the post is placed in the comments, but the notification email is not sent to the visitor.

If I edit a visitor's comment I see that the completed fields are:

Name, Email, Website

However the Email field contains my Admin email address and not the visitor's entered email.

What could be the issue with storing the visitor's email ?

Thanks

**Comment by jacobwb** [comment]
Hello, I have now fixed the issue of the admin email showing as the user's email. Please read the new section about notification emails in the FAQs section of the documentation. If you can confirm that the conditions for HashOver to send notifications are met in your case and that your server is not rejecting the emails, than I will look into the issue.

Also, consider getting the latest code, as it improves email delivery. If you are using a non-Latin language the latest changes might fix the issue for you.

**Comment by timoto** [comment]
Updated to latest version.

Notifications are now working as expected.
