### ISSUE TITLE
how to manange all comments at one place?

### ISSUE THREAD

**Issue by jzoy** [jacobwb/hashover-next#284]
Is there a way that I can manange all comments at one place?
I'm using hashover 2.0 for multiple site, but I have to check every single page for new comments.
Or could you tell me how to get notification when new comment posted.

**Comment by prisae** [comment]
You should get notifications, if you have set-up the email:
https://docs.barkdull.org/hashover-v2/setup

Maybe this also helps?
https://docs.barkdull.org/hashover-v2/faq#email-notifications-not-sent

**Comment by jzoy** [comment]
Thank for your help.
I did set up the email service but I olny can get notification when my comments get reply.
Could you tell me how to get notification for all comments(every single one) posted on my site?

**Comment by prisae** [comment]
If everything is set-up correctly then you should get notifications for all comments.

**Comment by jacobwb** [comment]
@jzoy @prisae is right, if email is working correctly on your server you should receive a notification email for every comment posted, however, you will not receive notifications when you post comments using the same email address as the admin `$notificationEmail` setting as explained here: https://docs.barkdull.org/hashover-v2/faq#email-notifications-not-sent. You might also not get notification emails when a person posts using an email your server thinks is spam.
