### ISSUE TITLE
Commenter login?

### ISSUE THREAD

**Issue by magix01** [jacobwb/hashover-next#292]
Hi, 

when i install hashover i can see that there is name and password field, i insert some credential and make a comment that is all good, but when i try to login with same name with different password it will accept the login, does hashover have real account system? What is password used for when everyone can login with same name and different password?

@jacmoe 

regards

**Comment by RianBergen** [comment]
> Hi,
> 
> when i install hashover i can see that there is name and password field, i insert some credential and make a comment that is all good, but when i try to login with same name with different password it will accept the login, does hashover have real account system? What is password used for when everyone can login with same name and different password?
> 
> @jacmoe
> 
> regards

@magix01 

Entering the same name and password allows you to edit and delete posts made by that exact name and password. Entering the same name and a different person will count as a different person and thus will not allow the editing/deleting of posts made by the first.

@jacobwb Please correct me if I am wrong.

**Comment by jacobwb** [comment]
@RianBergen That is correct, the password field tooltip says so as well. Another kind of related login credential is the email address, it doesn't change the login but changes what avatar gets displayed.

@magix01 Hope that helps.
