### ISSUE TITLE
Using a password without login is possible...?

### ISSUE THREAD

**Issue by JayCasee** [jacobwb/hashover-next#294]
First of all, thank you for this great works.

I'm wondering that... whether there is any setting to use a password only for the specific comment, not for login. E.g...

- When a user write a comment, the one inputs a password.

- All the comments shows edit button, regardless login status.

- But if a person wants to edit a specific comment, the one needs to input the password of the comment.

Is the above function is possible on the current HashOver 2.0...?

**Comment by jacobwb** [comment]
No this is not possible, because the edit form would show each users email address, that's why it is protected behind a login. If you disable the email field, you might be able to get this functionality with a minor change in the code if you really want to.
