### ISSUE TITLE
Unable to locate UI to approve comments

### ISSUE THREAD

**Issue by EMplIFil** [jacobwb/hashover-next#305]
Hi there,

I found this old issue (https://github.com/jacobwb/hashover-next/issues/137) about there being a dropdown menu to approve comments.

However, in a relatively recent version (I pulled the code maybe a few months ago at most) I am not able to find this dropdown menu, nor any other way to approve comments. I'm looking at the "Moderation" page from the admin section.

Thanks!

**Comment by oiseaumanifesto** [comment]
Pulled code today ( 69e22cf957e9a22eb9fe8b3fb6a9743c95ee38b5 ) and this issue seems to still be present. The "Moderation" page is blank.

**Comment by jacobwb** [comment]
I assume you both are running HashOver on a local server. This issue should now be fixed. Try refreshing any pages that use HashOver and then check the moderation page again.
