### ISSUE TITLE
How to view commenter's IP address?

### ISSUE THREAD

**Issue by EMplIFil** [jacobwb/hashover-next#308]
Hi there,

I see there is a setting to log user IP addresses, which is currently turned on.

Where can I view the IP address for each comment made?

**Comment by EMplIFil** [comment]
Found it in comments/threads/*/*.xml

**Comment by jacobwb** [comment]
Sorry for the delay, yes the IP addresses are stored in the comment files
or in the MySQL database. I will make a change soon to make the IP
addresses visible to admin, the IP addresses aren't shown for security
reasons, but there's no reason why admin shouldn't be able to see them.
