### ISSUE TITLE
Problem with a custom thread name

### ISSUE THREAD

**Issue by nsuomine** [jacobwb/hashover-next#338]
I use a custom thread name:

```
<script type="text/javascript">
var hashover = new HashOver ('hashover', {
      title: '[[*pagetitle]]',
      thread: 'article-[[*id]]',
});
```
For example,  thread name can be article-453. Posting comments and replying works well but editing and liking comments fail. I did some debugging and when I try to like or edit a comment, Hashover generates a thread name from the URL and does not use my custom thread name format. This will lead to an error because Hashover cannot find the comment from the database when $threadName variable has a wrong value.

**Comment by jacobwb** [comment]
Thank you for reporting this. The thread name was being passed to the AJAX likes and comment edit info scripts, but the scripts weren't actually using the thread name given to them. I have now fixed this issue. Please let me know if the problem persists.
