### ISSUE TITLE
Will stuff like a small 'latest post display' go in 2.x ?

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#53]
I had some ideas on how stuff like this could be implemented  but am wondering should this even be a topic for the current branch?

Example idea:

- once a new comment is written, also write the same comment in a file that stores cc 5-10 comments.
- we can then use the file to e.g. display a separate widget somewhere with the latest posts

Just wanted to throw a brainstorm out there, close or move if needed

**Comment by q2apro** [comment]
What is the recent progress of this?

I would also suggest to use a "latest.xml" and store the references to the recent comments. 

Only problems: 
1. if comment gets deleted by the user. 
2. if URL changes. 

However, these two points, I think, can be neglected.

**Comment by jacobwb** [comment]
It is not implemented yet.

I have it working with the code I'm working on right now, however, it has brought to my attention many problems with the current HashOver code that I'm currently working to fix.
