### ISSUE TITLE
HashOver 2.0 default layout: First Draft

### ISSUE THREAD

**Issue by jacobwb** [jacobwb/hashover-next#64]
Collapsed comments
---
![hashover-2 0-layout-draft-1](https://cloud.githubusercontent.com/assets/4677622/5218566/46804e22-7603-11e4-81a2-73b5b47204fc.png)

Full comments + reply forms
---
![hashover-2 0-layout-draft-2](https://cloud.githubusercontent.com/assets/4677622/5218595/7e372e94-7603-11e4-823f-a2bf5c7f90d8.png)

Updated edit and reply icons
---
![screenshot from 2014-11-27 06 53 24](https://cloud.githubusercontent.com/assets/4677622/5218625/a67e3df2-7603-11e4-8ea4-75ce4c679275.png)

I am posting this here for comments and suggestions. This updated layout will be pushed along with the other (much delayed) changes. The HashOver 1.0 style will be ported as necessary to work with 2.0 and be made available in the `style-sheets` directory, however, the style will likely be deprecated at some point, maybe even as soon as the release of version 2.1.

**Comment by Lux-Delux** [comment]
Nice progress :)

I'll also be making an update to my theme, a complete rewrite using css flex. Smaller, cleaner code etc.

It's late and this isn't much of input from me but just wanted to write something so you know I'm still alive heh.

**Comment by jacobwb** [comment]
@Lux-Delux

Thanks! Good to know.

Regarding your theme: The changes I'm going to be pushing in the next few days *have* messed up how your theme looks pretty badly, so a full rewrite would be a good idea ;D

**Comment by jacobwb** [comment]
The second draft is implemented now. If I make changes, or plan a whole new design/theme, I'll open another issue asking for opinions specifically related to that new design.

:-)
