### ISSUE TITLE
PHP Warnings for Cookie arguments

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#70]
Finally able to work with the new release. In any case everytime I post a test comment I get the following in my logs

`PHP message: PHP Warning:  Missing argument 3 for Cookies::set(), called in htdocs/hashover/scripts/writecomments.php on line 132 and defined in htdocs/hashover/scripts/cookies.php on line 46
PHP message: PHP Notice:  Undefined index: status in htdocs/hashover/scripts/writecomments.php on line 171
PHP message: PHP Warning:  Missing argument 3 for Cookies::set(), called in htdocs/hashover/scripts/writecomments.php on line 466 and defined in htdocs/hashover/scripts/cookies.php on line 46
PHP message: PHP Warning:  Missing argument 3 for Cookies::set(), called in htdocs/hashover/scripts/writecomments.php on line 467 and defined in htdocs/hashover/scripts/cookies.php on line 46" while reading response header from upstream`

Any ideas?

**Comment by jacobwb** [comment]
I must of overlooked potential warning messages. It should be fixed now.
