### ISSUE TITLE
Some basics on how to use API

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#74]
I'd like to implement Latest comments on my site.

My question is: what's the idea on how to use the provided  API files?

Should I include latest.php somewhere in order to call a function? Or, if I concluded correctly based on the theme widget files... there's a way to call the widget that already utilizes latest.php?

Thanks

**Comment by jacobwb** [comment]
It's used just like the normal HashOver script.

Like so:

    <div id="hashover-widget"></div>
    <script type="text/javascript" src="/hashover.js?api=latest"></script>

Key part: `?api=latest`

**Comment by Lux-Delux** [comment]
Oh, I knew it was something simple. Awesome, will try later

**Comment by Lux-Delux** [comment]
What about the count link? Can't seem to call it properly, what would be the correct variable to pass for api?
