### ISSUE TITLE
Like and Dislike functionality

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#75]
Nice to see you implement this.

Just wanted to clarify and perhaps brainstorm further improvements on it's functionality.

Here's what I noticed when trying it out:

Click on like:
- displays 1 like and the Liked link appears. When it's clicked the like dissapears (if this is intended then perhaps make it say Unlike or something)
- However when I now click Like again it doesn't stay Liked after refresh
- Same goes for Dislike

In any case Unliking/UnDisliking breaks something

**Comment by jacobwb** [comment]
1. This is intended. Will do.
2. This should be fixed now.
3. This should be fixed now.

**Comment by jacobwb** [comment]
1. Maybe something like?

  ![untitled](https://cloud.githubusercontent.com/assets/4677622/6766510/2e493bee-cfc6-11e4-8705-20fcf06fe0f1.png)

**Comment by Lux-Delux** [comment]
Looks fine to me :)
