### ISSUE TITLE
Logged out user get's logged in automatically

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#77]
Let's say I post a comment using just a name, I get logged in by default.

I log out, then post a comment as anonymous and I automatically get logged in.

Is this intended ?

**Comment by jacobwb** [comment]
Yes it is.

I figure:

1. User enters name, password, etc.
2. User posts comment.
3. User continues posting/replying without having to see the name, password, etc inputs.

It seemed logical to me. Is it confusing?

**Comment by Lux-Delux** [comment]
That sounds logical yes.

I was only thinking from a perspective if a user wants to change his name. In that case he would need to clear cookies right?

Though that might be a rare use case. Need to think on it more

**Comment by jacobwb** [comment]
Well, they would need to logout and log back in, is all.

**Comment by Lux-Delux** [comment]
Yes if they enter a new name, but not if they want anonymous.

Don't know if it's really an issue currently

**Comment by jacobwb** [comment]
Oh, I see. That is a bug. It should be fixed now.
