### ISSUE TITLE
On page reload user doesn't get sent to comment anchor

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#78]
I've been testing this on my test page which doesn't have any other js interference.

As the title says, after making a new post the user stays at page top, even though the url has the anchor. Same goes for logging in.

Only on my end?

**Comment by Lux-Delux** [comment]
Seems to work fine in Firefox, Chrome is probably giving me trouble, will report back

**Comment by jacobwb** [comment]
I was having a similar problem getting Chrome to jump to the top of the comments a little while ago as well. It seems that in Chrome there is what should only be called a bug, where anchor "jump" tags aren't followed if the linked element isn't on the page before the page begins loading.

I've added a little workaround, see if it works for you now.

**Comment by Lux-Delux** [comment]
Thanks, seems to be working fine now :)
