### ISSUE TITLE
Add specific class for Be the first to comment! div

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#82]
I couldn't figure out where to change this in code.

Currently, the div class is the same for the notice and for the first actual comments.

So if you for example add a background color for .hashover-header and some padding, it will appear above the notice and look ugly

PS. Where is the string to change the text?

**Comment by jacobwb** [comment]
I just moved the "hashover-first" and "hashover-deleted" classes into the "hashover-comment" attribute. There is no reason for those classes to be applied to "hashover-content", as far as I see.

So now just, for example:

```
#hashover .hashover-first .hashover-header {
    display: none;
}
```
Will hide the header of the "Be the first to comment!" message.
___
The "Be the first to comment!" string is stored in the locales.

English: 
>[`'first_cmt'	=> 'Be the first to comment!',`](https://github.com/jacobwb/hashover-next/blob/master/hashover/scripts/locales/en.php#L84)

German:
>[`'first_cmt'	=> 'Seien den ersten Kommentar!',`](https://github.com/jacobwb/hashover-next/blob/master/hashover/scripts/locales/de.php#L84)

Spanish:
>[`'first_cmt'	=> '¡Ser el primero en comentar!',`](https://github.com/jacobwb/hashover-next/blob/master/hashover/scripts/locales/es.php#L84)

French:
>[`'first_cmt'	=> 'Soyez le premier à commenter!',`](https://github.com/jacobwb/hashover-next/blob/master/hashover/scripts/locales/fr.php#L84)

Japanese:
>[`'first_cmt'	=> 'あなたが最初のコメントを付けて！',`](https://github.com/jacobwb/hashover-next/blob/master/hashover/scripts/locales/jp.php#L84)

**Comment by Lux-Delux** [comment]
Nice.

Duh! Didn't even look at the locales folder
