### ISSUE TITLE
Latest Widget displaying only current page posts

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#89]
I know we talked about this somewhere down the line.

So the way it works now is intentional? 

It would make more usability sense if it could be used across the website showing latest posts in general from all the pages.

Something like:
- there's an additional general JSON or XML file
- user makes a post and link to it is written to the file
- Latest widget parses the comments

**Comment by jacobwb** [comment]
Add `&global=yes` to the end of the `src` attribute.

Like so:

```
<script type="text/javascript" src="/hashover.js?api=latest&global=yes"></script>
```
