### ISSUE TITLE
API count can't write

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#90]
`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

In Chrome inspector

**Comment by jacobwb** [comment]
This should be fixed now.

Sorry, I was using it like this:

```
<script type="text/javascript" src="/hashover/api/count_link.php?url=..."></script>
```

Which executes it synchronously.

**Comment by Lux-Delux** [comment]
Awesome, works fine now and the functionality is great
