### ISSUE TITLE
Logged in user with email outputs wrong link

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#91]
So if I log in with an email, let's say tester@test and make a reply, my name is output as link like this

`<a id="hashover-name-c1r1r2r1" href="http://tester@test" target="_blank">Tester</a>`

Is this supposed to be a mailto link?

EDIT: When logging out the email field is filled like this:

`http://tester@test`

**Comment by jacobwb** [comment]
Are you sure you aren't typing your e-mail into the website field?

It's not happening for me.

**Comment by Lux-Delux** [comment]
LMAO I'm a moron
