### ISSUE TITLE
Add option to trim widget comment

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#94]
While I was thinking on how to best implement the latest widget on my site I noticed the comments are shown complete.

This makes the widget potentially unusable in a sidebar etc. when the comment is long.

Some kind of string limiting on the output with an '...' at the end would be good to have as an option.

Perhaps this would be simplest
http://php.net/manual/en/function.mb-strimwidth.php

**Comment by jacobwb** [comment]
There ya go~

It's not been well tested obviously. If you could play around with it and tell me what you think a good default trim length would be, that'd be helpful :-)

**Comment by Lux-Delux** [comment]
Highly depends on where it's used so... 100 looks like a good starting point from my quick tests.

**Comment by jacobwb** [comment]
Awesome!
