### ISSUE TITLE
Reply form avatar image

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#96]
First a bug: when I'm logged in with a gravatar image, the reply form still shows that first-comment image.

Second: I propose the image be removed from the form. If the user is logged in and wants to reply, all he needs is the input text field and submit buttons (easy and simple without clutter).

**Comment by jacobwb** [comment]
- First: Is fixed.

- Second: The image is removed when icons are disabled. The idea is to show the user what the comment will look like once it's posted. So there's an image when they are enabled.

**Comment by Lux-Delux** [comment]
Another bug? When i log out my gravatar image is still displayed

**Comment by jacobwb** [comment]
Displayed where?

**Comment by Lux-Delux** [comment]
Ooops sorry, it's shown next to the main input fields

**Comment by jacobwb** [comment]
The plan is to have that automatically change as you enter your e-mail.
Should it just be the first-comment image instead?

**Comment by Lux-Delux** [comment]
Well it makes no sense to show the users image if he logs out.

I guess reverting to default makes most sense

**Comment by jacobwb** [comment]
I changed it, it should be that way now.

**Comment by Lux-Delux** [comment]
Works
