### ISSUE TITLE
Optional login/logout functionality

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#97]
I consider the login/logout buttons confusing for the end user, thus I'd like to remove them. To further promote commenting, I don't want people to even think of what that login button means (imo people are stupid no matter how clear it is to us)

Now I need to go take the dog for a walk but please discuss and maybe we can brainstorm the whole functionality.

**Comment by Lux-Delux** [comment]
Been thinking some more on this...

Why not just remove the Login button? With posting a comment the user gets logged in anyway.

This way the functionality doesn't change but things get simpler for the end user.

**Comment by jacobwb** [comment]
Perhaps the first comment shouldn't auto-login the user. Then the buttons can simply be hidden with CSS or disabled in settings. Maybe auto-login should only happen on first comment when login functionality is enabled and it wouldn't when it's disabled?

> Why not just remove the Login button?

Because users need to eventually login to edit/delete comments once the cookies expire or if they are on a different computer or browser. That's why it was added in the first place.

**Comment by Lux-Delux** [comment]
On the edit note I'll open another ticket as I just noticed something.

I need to test some styling with the login button to see other possible solutions.

**Comment by Lux-Delux** [comment]
I guess the problem is my particular use case.

Since I'm not using the password field, editing is not possible.

Thus I have no use for the login button right? As essentially if a logged out user returns and posts with the same mail he'll be logged back in.

**Comment by jacobwb** [comment]
> Thus I have no use for the login button right? As essentially if a logged out user returns and posts with the same mail he'll be logged back in.

Well... a user might still like to logout to change their name or e-mail.

**Comment by Lux-Delux** [comment]
Yeah I have no problem with logout, but login makes no sense, that's what I meant for my use case.

Dunno, I'll probably remove it manually with each update. If I had SSL I'd probably keep it together with the password field

**Comment by jacobwb** [comment]
I just noticed the Login and Logout buttons both had "hashover-login" as a class, now the Logout button has "hashover-logout" as a class. So if you want, you could just hide it with CSS.

```css
.hashover-logout {
    display: none;
}
```
