### ISSUE TITLE
No edit button

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#98]
Just noticed I can't edit a post, there's no Edit Button. It's there in the layout html. 

Don't know why. You can try it on my test page

**Comment by jacobwb** [comment]
You disabled the password field.
Users can only edit a comment if they give a password.
Which... you can't do without a password field.

;-]

**Comment by Lux-Delux** [comment]
That makes sense.

Guess I won't use that functionality... kinda want to avoid password inputs over a regular http connection.
