### ISSUE TITLE
Optional gravatar identicons

### ISSUE THREAD

**Issue by Lux-Delux** [jacobwb/hashover-next#99]
As I understand, one can use Gravatar to return their identicon generated images

e.g. http://joshtronic.com/2014/01/20/gravatar-as-an-identicon-generation-service/

Since we're already using Gravatar, why not implement this feature to show identicons instead of default if one so chooses.

What I mean, show identicon if there's no avatar for the mail

**Comment by jacobwb** [comment]
All of Gravatar's supported "themed" (as I will call them) avatars are now supported, along with the option to force the theme to be used instead of user image avatars.

**Comment by Lux-Delux** [comment]
Awesome! You're fast :+1:

**Comment by jacobwb** [comment]
Thanks ;)

I just tweaked it a little.

**Comment by Lux-Delux** [comment]
Are your default images replaced by identicons?

`public $icon_mode		= 'image';			// How to display avatar icons (either 'image', 'count' or 'none')
public $gravatar_default	= 'retro';				// Gravatar theme to use ('mm', 'identicon', 'monsterid', 'wavatar', or 'retro')
public $gravatar_force		= 'no';`

The default image is shown, no identicons

**Comment by jacobwb** [comment]
Try the latest files if you haven't.

The behavior should be...

With...

```php
public $gravatar_default = 'retro';
public $gravatar_force   = 'no';
```

    Comment has e-mail and a Gravatar image == Gravatar image is shown.
    Comment has e-mail but no Gravatar image == Gravatar retro image is shown.
    Comment has no e-mail == local avatar image is shown.

With...

```php
public $gravatar_default = 'retro';
public $gravatar_force   = 'yes';
```

    Comment has e-mail and a Gravatar image == Gravatar retro image is shown.
    Comment has e-mail but no Gravatar image == Gravatar retro image is shown.
    Comment has no e-mail == local avatar image is shown.

Any kind of identicon cannot be generated without an e-mail address, so the local default avatar icon image `hashover/images/pngs/avatar.png` is loaded instead.

**Comment by Lux-Delux** [comment]
Ah my test users didn't have mail. 

Actually it can be generated with any hash no?

**Comment by jacobwb** [comment]
Yes, but what are you going to use to generate the hash?
It has to be unique, or else it's pointless. That's why an e-mail address is what is used by Gravatar.
Username + password might work as an alternative, though.

**Comment by Lux-Delux** [comment]
Yeah I was thinking on what would be used if user supplied nothing but the comment. Would still be cool for that particular user to have an image instead of default.

Though really one can't do much in that case
